In [18]:
import pandas as pd
import numpy as np

In [19]:
tr_bmw = pd.read_excel("C:/Users/lravlic/Downloads/Transito DP_BMW_S25.xlsx",dtype={'Nº.pedido.compra':'str','CANT':'int64','Cód.N..de.parte(empa':'str','FACTURA':'str'})

In [20]:
tr_bmw.rename(columns={'Tipo.pedido':'Vía','Cód.N..de.parte(empa':'Material','CANT':'Cantidad','Nº.pedido.compra':'Doc. Compra'}, inplace=True)

In [30]:
cond = [tr_bmw['Vía'] == 'Courier', tr_bmw['Vía'] == 'Aéreo', tr_bmw['Vía'] == 'Marítimo']
opc = [10, 20, 90]
tr_bmw['Dias'] = np.select(cond, opc, default=0)

# Asegúrate de que 'Fecha.creación' sea tipo datetime
tr_bmw['Fecha.creación'] = pd.to_datetime(tr_bmw['Fecha.creación'])

# Calculamos fecha estimada sumando los días
fecha_estim = tr_bmw['Fecha.creación'] + pd.to_timedelta(tr_bmw['Dias'], unit='D')

# Llenamos los valores faltantes en 'ESTIMADA DISPO' con esa fecha calculada
tr_bmw['ESTIMADA DISPO'] = pd.to_datetime(tr_bmw['ESTIMADA DISPO'])
tr_bmw['FechaFinal'] = tr_bmw['ESTIMADA DISPO'].fillna(fecha_estim)

In [31]:
tr_bmw

,Vía,Doc. Compra,Material,Cantidad,Status.línea.pedido,Fecha.creación,FACTURA,ESTIMADA DISPO,Dias,FechaFinal
0,Marítimo,2518,C77452456667,2,O,2024-05-25,NaN,NaT,90,2024-08-23
1,Marítimo,2680,B12638645514,1,A,2024-08-07,8721893953,2025-08-20,90,2025-08-20
2,Marítimo,2752,C77495B5C6D7,8,O,2024-09-03,NaN,NaT,90,2024-12-02
3,Marítimo,2754,M80285B32101,15,O,2024-09-05,NaN,NaT,90,2024-12-04
4,Marítimo,2754,M80285B32104,15,O,2024-09-05,NaN,NaT,90,2024-12-04
...,...,...,...,...,...,...,...,...,...,...
3839,Marítimo,3453,B51727390750,4,O,2025-06-16,NaN,NaT,90,2025-09-14
3840,Marítimo,3453,B61445A92D00,120,O,2025-06-16,NaN,NaT,90,2025-09-14
3841,Marítimo,3453,B61448490517,120,O,2025-06-16,NaN,NaT,90,2025-09-14
3842,Marítimo,3453,B31108866774,8,O,2025-06-16,NaN,NaT,90,2025-09-14
3843,Aéreo,3454,B32307938709,2,O,2025-06-16,NaN,NaT,20,2025-07-06